name:                c-compiler
version:             1.0.0.0
github:              "t-sasaki915/c-compiler"
license:             MIT
author:              "Sasaki Touma"
maintainer:          "netst915@gmail.com"
copyright:           "2024 Sasaki Touma"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/c-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 5.2 && < 5.3
- HUnit >= 1.6 && < 1.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  c-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-compiler

tests:
  c-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-compiler
    - HUnit
